global:
  scrape_interval: 5s # How often to scrape targets by default.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "nodejs-app"
    static_configs:
      - targets: ["app:3000"]
